import type { Component } from 'svelte';
import {
  Aurora,
  auroraPresets,
  Caustics,
  causticsPresets,
  Frost,
  frostPresets,
  Smoke,
  smokePresets,
  Rain,
  rainPresets,
  ColorPanels,
  colorPanelsPresets,
  Dithering,
  ditheringPresets,
  DotGrid,
  dotGridPresets,
  DotOrbit,
  dotOrbitPresets,
  FlutedGlass,
  flutedGlassPresets,
  GodRays,
  godRaysPresets,
  GrainGradient,
  grainGradientPresets,
  HalftoneCmyk,
  halftoneCmykPresets,
  HalftoneDots,
  halftoneDotsPresets,
  Heatmap,
  heatmapPresets,
  ImageDithering,
  imageDitheringPresets,
  LiquidMetal,
  liquidMetalPresets,
  MeshGradient,
  meshGradientPresets,
  Metaballs,
  metaballsPresets,
  NeuroNoise,
  neuroNoisePresets,
  PaperTexture,
  paperTexturePresets,
  PerlinNoise,
  perlinNoisePresets,
  PulsingBorder,
  pulsingBorderPresets,
  SimplexNoise,
  simplexNoisePresets,
  SmokeRing,
  smokeRingPresets,
  Spiral,
  spiralPresets,
  StaticMeshGradient,
  staticMeshGradientPresets,
  StaticRadialGradient,
  staticRadialGradientPresets,
  Swirl,
  swirlPresets,
  Voronoi,
  voronoiPresets,
  Warp,
  warpPresets,
  Water,
  waterPresets,
  Waves,
  wavesPresets,
} from '$lib';
import { flatHomeThumbnails } from './home-thumbnails.js';
import ColorDemoColorspace from './pages/ColorDemoColorspace.svelte';
import ColorDemoSoftness from './pages/ColorDemoSoftness.svelte';
import ColorDemoSteps from './pages/ColorDemoSteps.svelte';

export type ShaderDemoEntry = {
  kind: 'shader';
  slug: string;
  title: string;
  importName: string;
  ShaderComponent: Component<any>;
  presets: ReadonlyArray<{ name: string; params: Record<string, unknown> }>;
  previewImage?: string;
  sampleImageSet?: 'image-filters' | 'logos';
};

export type CustomDemoEntry = {
  kind: 'custom';
  slug: string;
  title: string;
  Component: Component<any>;
};

export type DemoEntry = ShaderDemoEntry | CustomDemoEntry;

const previewBySlug = Object.fromEntries(flatHomeThumbnails.map((s) => [s.url.replace(/^\//, ''), s.image]));

export const demoRegistry: Record<string, DemoEntry> = {
  aurora: {
    kind: 'shader',
    slug: 'aurora',
    title: 'Aurora',
    importName: 'Aurora',
    ShaderComponent: Aurora,
    presets: auroraPresets,
    previewImage: previewBySlug['aurora'],
  },
  caustics: {
    kind: 'shader',
    slug: 'caustics',
    title: 'Caustics',
    importName: 'Caustics',
    ShaderComponent: Caustics,
    presets: causticsPresets,
    previewImage: previewBySlug['caustics'],
  },
  frost: {
    kind: 'shader',
    slug: 'frost',
    title: 'Frost',
    importName: 'Frost',
    ShaderComponent: Frost,
    presets: frostPresets,
    previewImage: previewBySlug['frost'],
  },
  smoke: {
    kind: 'shader',
    slug: 'smoke',
    title: 'Smoke',
    importName: 'Smoke',
    ShaderComponent: Smoke,
    presets: smokePresets,
    previewImage: previewBySlug['smoke'],
  },
  rain: {
    kind: 'shader',
    slug: 'rain',
    title: 'Rain',
    importName: 'Rain',
    ShaderComponent: Rain,
    presets: rainPresets,
    previewImage: previewBySlug['rain'],
  },
  'mesh-gradient': {
    kind: 'shader',
    slug: 'mesh-gradient',
    title: 'Mesh Gradient',
    importName: 'MeshGradient',
    ShaderComponent: MeshGradient,
    presets: meshGradientPresets,
    previewImage: previewBySlug['mesh-gradient'],
  },
  'static-mesh-gradient': {
    kind: 'shader',
    slug: 'static-mesh-gradient',
    title: 'Static Mesh Gradient',
    importName: 'StaticMeshGradient',
    ShaderComponent: StaticMeshGradient,
    presets: staticMeshGradientPresets,
    previewImage: previewBySlug['static-mesh-gradient'],
  },
  'static-radial-gradient': {
    kind: 'shader',
    slug: 'static-radial-gradient',
    title: 'Static Radial Gradient',
    importName: 'StaticRadialGradient',
    ShaderComponent: StaticRadialGradient,
    presets: staticRadialGradientPresets,
    previewImage: previewBySlug['static-radial-gradient'],
  },
  dithering: {
    kind: 'shader',
    slug: 'dithering',
    title: 'Dithering',
    importName: 'Dithering',
    ShaderComponent: Dithering,
    presets: ditheringPresets,
    previewImage: previewBySlug['dithering'],
  },
  'grain-gradient': {
    kind: 'shader',
    slug: 'grain-gradient',
    title: 'Grain Gradient',
    importName: 'GrainGradient',
    ShaderComponent: GrainGradient,
    presets: grainGradientPresets,
    previewImage: previewBySlug['grain-gradient'],
  },
  'dot-orbit': {
    kind: 'shader',
    slug: 'dot-orbit',
    title: 'Dot Orbit',
    importName: 'DotOrbit',
    ShaderComponent: DotOrbit,
    presets: dotOrbitPresets,
    previewImage: previewBySlug['dot-orbit'],
  },
  'dot-grid': {
    kind: 'shader',
    slug: 'dot-grid',
    title: 'Dot Grid',
    importName: 'DotGrid',
    ShaderComponent: DotGrid,
    presets: dotGridPresets,
    previewImage: previewBySlug['dot-grid'],
  },
  warp: {
    kind: 'shader',
    slug: 'warp',
    title: 'Warp',
    importName: 'Warp',
    ShaderComponent: Warp,
    presets: warpPresets,
    previewImage: previewBySlug['warp'],
  },
  spiral: {
    kind: 'shader',
    slug: 'spiral',
    title: 'Spiral',
    importName: 'Spiral',
    ShaderComponent: Spiral,
    presets: spiralPresets,
    previewImage: previewBySlug['spiral'],
  },
  swirl: {
    kind: 'shader',
    slug: 'swirl',
    title: 'Swirl',
    importName: 'Swirl',
    ShaderComponent: Swirl,
    presets: swirlPresets,
    previewImage: previewBySlug['swirl'],
  },
  waves: {
    kind: 'shader',
    slug: 'waves',
    title: 'Waves',
    importName: 'Waves',
    ShaderComponent: Waves,
    presets: wavesPresets,
    previewImage: previewBySlug['waves'],
  },
  'neuro-noise': {
    kind: 'shader',
    slug: 'neuro-noise',
    title: 'Neuro Noise',
    importName: 'NeuroNoise',
    ShaderComponent: NeuroNoise,
    presets: neuroNoisePresets,
    previewImage: previewBySlug['neuro-noise'],
  },
  'perlin-noise': {
    kind: 'shader',
    slug: 'perlin-noise',
    title: 'Perlin Noise',
    importName: 'PerlinNoise',
    ShaderComponent: PerlinNoise,
    presets: perlinNoisePresets,
    previewImage: previewBySlug['perlin-noise'],
  },
  'simplex-noise': {
    kind: 'shader',
    slug: 'simplex-noise',
    title: 'Simplex Noise',
    importName: 'SimplexNoise',
    ShaderComponent: SimplexNoise,
    presets: simplexNoisePresets,
    previewImage: previewBySlug['simplex-noise'],
  },
  voronoi: {
    kind: 'shader',
    slug: 'voronoi',
    title: 'Voronoi',
    importName: 'Voronoi',
    ShaderComponent: Voronoi,
    presets: voronoiPresets,
    previewImage: previewBySlug['voronoi'],
  },
  'pulsing-border': {
    kind: 'shader',
    slug: 'pulsing-border',
    title: 'Pulsing Border',
    importName: 'PulsingBorder',
    ShaderComponent: PulsingBorder,
    presets: pulsingBorderPresets,
    previewImage: previewBySlug['pulsing-border'],
  },
  metaballs: {
    kind: 'shader',
    slug: 'metaballs',
    title: 'Metaballs',
    importName: 'Metaballs',
    ShaderComponent: Metaballs,
    presets: metaballsPresets,
    previewImage: previewBySlug['metaballs'],
  },
  'color-panels': {
    kind: 'shader',
    slug: 'color-panels',
    title: 'Color Panels',
    importName: 'ColorPanels',
    ShaderComponent: ColorPanels,
    presets: colorPanelsPresets,
    previewImage: previewBySlug['color-panels'],
  },
  'smoke-ring': {
    kind: 'shader',
    slug: 'smoke-ring',
    title: 'Smoke Ring',
    importName: 'SmokeRing',
    ShaderComponent: SmokeRing,
    presets: smokeRingPresets,
    previewImage: previewBySlug['smoke-ring'],
  },
  'god-rays': {
    kind: 'shader',
    slug: 'god-rays',
    title: 'God Rays',
    importName: 'GodRays',
    ShaderComponent: GodRays,
    presets: godRaysPresets,
    previewImage: previewBySlug['god-rays'],
  },
  'paper-texture': {
    kind: 'shader',
    slug: 'paper-texture',
    title: 'Paper Texture',
    importName: 'PaperTexture',
    ShaderComponent: PaperTexture,
    presets: paperTexturePresets,
    previewImage: previewBySlug['paper-texture'],
    sampleImageSet: 'image-filters',
  },
  'fluted-glass': {
    kind: 'shader',
    slug: 'fluted-glass',
    title: 'Fluted Glass',
    importName: 'FlutedGlass',
    ShaderComponent: FlutedGlass,
    presets: flutedGlassPresets,
    previewImage: previewBySlug['fluted-glass'],
    sampleImageSet: 'image-filters',
  },
  water: {
    kind: 'shader',
    slug: 'water',
    title: 'Water',
    importName: 'Water',
    ShaderComponent: Water,
    presets: waterPresets,
    previewImage: previewBySlug['water'],
    sampleImageSet: 'image-filters',
  },
  'image-dithering': {
    kind: 'shader',
    slug: 'image-dithering',
    title: 'Image Dithering',
    importName: 'ImageDithering',
    ShaderComponent: ImageDithering,
    presets: imageDitheringPresets,
    previewImage: previewBySlug['image-dithering'],
    sampleImageSet: 'image-filters',
  },
  'halftone-dots': {
    kind: 'shader',
    slug: 'halftone-dots',
    title: 'Halftone Dots',
    importName: 'HalftoneDots',
    ShaderComponent: HalftoneDots,
    presets: halftoneDotsPresets,
    previewImage: previewBySlug['halftone-dots'],
    sampleImageSet: 'image-filters',
  },
  'halftone-cmyk': {
    kind: 'shader',
    slug: 'halftone-cmyk',
    title: 'Halftone CMYK',
    importName: 'HalftoneCmyk',
    ShaderComponent: HalftoneCmyk,
    presets: halftoneCmykPresets,
    previewImage: previewBySlug['halftone-cmyk'],
    sampleImageSet: 'image-filters',
  },
  heatmap: {
    kind: 'shader',
    slug: 'heatmap',
    title: 'Heatmap',
    importName: 'Heatmap',
    ShaderComponent: Heatmap,
    presets: heatmapPresets,
    previewImage: previewBySlug['heatmap'],
    sampleImageSet: 'logos',
  },
  'liquid-metal': {
    kind: 'shader',
    slug: 'liquid-metal',
    title: 'Liquid Metal',
    importName: 'LiquidMetal',
    ShaderComponent: LiquidMetal,
    presets: liquidMetalPresets,
    previewImage: previewBySlug['liquid-metal'],
    sampleImageSet: 'logos',
  },
  'color-demo-colorspace': {
    kind: 'custom',
    slug: 'color-demo-colorspace',
    title: 'Color Demo: Color Space',
    Component: ColorDemoColorspace,
  },
  'color-demo-steps': {
    kind: 'custom',
    slug: 'color-demo-steps',
    title: 'Color Demo: Steps',
    Component: ColorDemoSteps,
  },
  'color-demo-softness': {
    kind: 'custom',
    slug: 'color-demo-softness',
    title: 'Color Demo: Softness',
    Component: ColorDemoSoftness,
  },
};

export function getDemoEntry(slug: string): DemoEntry | undefined {
  return demoRegistry[slug];
}
